CREATE TABLE IF NOT EXISTS chats (
 id BIGINT PRIMARY KEY
 chat_id BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS links (
 id BIGINT PRIMARY KEY,
 chat_id BIGINT NOT NULL FOREIGN KEY
 link_url VARCHAR ( 255 ) NOT NULL
 datetimestamp TIMESTAMP NOT NULL,
 FOREIGN KEY (chat_id) REFERENCES chats (chat_id),

);
