on:
  push:
    paths:
      - 'scrapper/**'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: scrapper_image

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Build JAR
        run: mvn -DskipTests=true package -pl scrapper -am
      - name: Build Image
        run: docker build -q -t $REGISTRY/arsiharsi/$IMAGE_NAME:latest . -f scrapper.Dockerfile
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GIT_DOCKER_PAT}}

      - name: 'Push Inventory Image'
        run: |
          docker push $REGISTRY/arsiharsi/$IMAGE_NAME:latest